# Generated by Django 6.0.3 on 2026-04-04 18:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_rates', models.JSONField(blank=True, default=dict, help_text='Operator-specific SMS rates. Format: {"gp": {"masking": 0.30, "non_masking": 0.25}, ...}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default Rate',
                'verbose_name_plural': 'Default Rates',
                'db_table': 'default_rates',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Gateway name (e.g., SSLCommerz Primary)', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Gateway logo image (recommended size: 120x40px)', null=True, upload_to=core.models.gateway_logo_path)),
                ('gateway_class', models.CharField(choices=[('SSLCOMMERZ', 'SSLCommerz'), ('BKASH', 'bKash')], default='SSLCOMMERZ', help_text='Payment gateway class to use', max_length=50)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Gateway credentials in JSON format (store_id, store_pass, etc.)')),
                ('tdr', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction Discount Rate (TDR) in percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is this gateway active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'payment_gateways',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provider name (e.g., ReveSMS Primary)', max_length=100)),
                ('provider_class', models.CharField(choices=[('REVESMS', 'ReveSMS')], default='REVESMS', help_text='Provider class to use for sending SMS', max_length=50)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Provider credentials in JSON format')),
                ('masking_rate', models.DecimalField(decimal_places=2, default=0.35, help_text='Rate per SMS for masking (in BDT)', max_digits=10)),
                ('non_masking_rate', models.DecimalField(decimal_places=2, default=0.25, help_text='Rate per SMS for non-masking (in BDT)', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current provider balance (in BDT)', max_digits=12)),
                ('balance_last_updated', models.DateTimeField(blank=True, help_text='Last time balance was synced', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this provider active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
                'db_table': 'sms_providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SenderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(help_text='Sender ID (e.g., SMS-GW, MyBrand)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(help_text='Associated SMS Provider', on_delete=django.db.models.deletion.CASCADE, related_name='sender_ids', to='core.smsprovider')),
            ],
            options={
                'verbose_name': 'Sender ID',
                'verbose_name_plural': 'Sender IDs',
                'db_table': 'sender_ids',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'sender_id')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(help_text='11-digit Bangladeshi mobile number (e.g., 01712345678)', max_length=11, validators=[core.models.validate_bd_mobile_number])),
                ('photo', models.ImageField(blank=True, default='images/administrator.jpg', help_text='Profile photo', null=True, upload_to=core.models.user_profile_photo_path)),
                ('balance', models.DecimalField(decimal_places=2, default=5.0, help_text='Account balance in BDT', max_digits=10)),
                ('company_name', models.CharField(blank=True, help_text='Company or organization name', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, help_text='Job title or designation', max_length=100, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address', null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography or description', null=True)),
                ('masking_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Custom masking SMS rate (per SMS). Leave empty to use provider default.', max_digits=10, null=True)),
                ('non_masking_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Custom non-masking SMS rate (per SMS). Leave empty to use provider default.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('default_provider', models.ForeignKey(blank=True, help_text='Default SMS provider for this user. If not set, system default will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='core.smsprovider')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSenderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is this sender ID active for the user?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_id', models.ForeignKey(help_text='Assigned sender ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.senderid')),
                ('user', models.ForeignKey(help_text='User who owns this sender ID', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sender_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sender ID',
                'verbose_name_plural': 'User Sender IDs',
                'db_table': 'user_sender_ids',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'sender_id')},
            },
        ),
    ]
