# Generated by Django 6.0.3 on 2026-04-03 15:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='images/administrator.jpg', help_text='Profile photo', null=True, upload_to=core.models.user_profile_photo_path),
        ),
    ]
