# Generated by Django 6.0.3 on 2026-04-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprovider',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'SMS Provider', 'verbose_name_plural': 'SMS Providers'},
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default provider? Only one provider can be default at a time.'),
        ),
    ]
