# Generated by Django 6.0.3 on 2026-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_smsprovider_options_smsprovider_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_class',
            field=models.CharField(choices=[('SSLCOMMERZ', 'SSLCommerz'), ('AAMARPAY', 'aamarPay'), ('BKASH', 'bKash')], default='SSLCOMMERZ', help_text='Payment gateway class to use', max_length=50),
        ),
    ]
