# Generated by Django 6.0.3 on 2026-04-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masking_rate', models.DecimalField(decimal_places=2, default=0.35, help_text='Default rate per SMS for masking (in BDT)', max_digits=10)),
                ('non_masking_rate', models.DecimalField(decimal_places=2, default=0.25, help_text='Default rate per SMS for non-masking (in BDT)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default Rate',
                'verbose_name_plural': 'Default Rates',
                'db_table': 'default_rates',
            },
        ),
    ]
