# Generated by Django 6.0.3 on 2026-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_defaultrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provider name (e.g., ReveSMS Primary)', max_length=100)),
                ('provider_class', models.CharField(choices=[('REVESMS', 'ReveSMS')], default='REVESMS', help_text='Provider class to use for sending SMS', max_length=50)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Provider credentials (API key, secret, etc.) in JSON format')),
                ('is_active', models.BooleanField(default=True, help_text='Is this provider active?')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
                'db_table': 'sms_providers',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
