# Generated by Django 6.0.3 on 2026-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_smsprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsprovider',
            name='masking_rate',
            field=models.DecimalField(decimal_places=2, default=0.35, help_text='Rate per SMS for masking (in BDT)', max_digits=10),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='non_masking_rate',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Rate per SMS for non-masking (in BDT)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Provider credentials in JSON format'),
        ),
    ]
