# Generated by Django 6.0.3 on 2026-04-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_smsprovider_masking_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(help_text='Sender ID (e.g., SMS-GW, MyBrand)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this sender ID active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(help_text='Associated SMS Provider', on_delete=django.db.models.deletion.CASCADE, related_name='sender_ids', to='core.smsprovider')),
            ],
            options={
                'verbose_name': 'Sender ID',
                'verbose_name_plural': 'Sender IDs',
                'db_table': 'sender_ids',
                'ordering': ['-is_active', '-created_at'],
                'unique_together': {('provider', 'sender_id')},
            },
        ),
    ]
