# Generated by Django 6.0.3 on 2026-04-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_senderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Gateway name (e.g., SSLCommerz Primary)', max_length=100)),
                ('gateway_class', models.CharField(choices=[('SSLCOMMERZ', 'SSLCommerz'), ('BKASH', 'bKash')], default='SSLCOMMERZ', help_text='Payment gateway class to use', max_length=50)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Gateway credentials in JSON format (store_id, store_pass, etc.)')),
                ('tdr', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction Discount Rate (TDR) in percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is this gateway active?')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'payment_gateways',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
