# Generated by Django 6.0.3 on 2026-04-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='masking_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom masking SMS rate (per SMS). Leave empty to use provider default.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='non_masking_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom non-masking SMS rate (per SMS). Leave empty to use provider default.', max_digits=10, null=True),
        ),
    ]
