# Generated by Django 6.0.3 on 2026-04-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_masking_rate_profile_non_masking_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultrate',
            name='credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Operator-specific SMS rates (JSON format)'),
        ),
    ]
