# Generated by Django 6.0.3 on 2026-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_smsprovider_is_active_and_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprovider',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS Provider', 'verbose_name_plural': 'SMS Providers'},
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current provider balance (in BDT)', max_digits=12),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='balance_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time balance was synced', null=True),
        ),
    ]
