# Generated by Django 6.0.3 on 2026-04-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_smsprovider_options_smsprovider_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsprovider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this provider active?'),
        ),
    ]
