# Generated by Django 6.0.3 on 2026-04-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_smsprovider_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senderid',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sender ID', 'verbose_name_plural': 'Sender IDs'},
        ),
        migrations.RemoveField(
            model_name='senderid',
            name='is_active',
        ),
    ]
