# Generated by Django 6.0.3 on 2026-04-04 08:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_senderid_options_remove_senderid_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Gateway', 'verbose_name_plural': 'Payment Gateways'},
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='logo',
            field=models.ImageField(blank=True, help_text='Gateway logo image (recommended size: 120x40px)', null=True, upload_to=core.models.gateway_logo_path),
        ),
    ]
