# Generated by Django 6.0.3 on 2026-04-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_gateway_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='is_default',
        ),
    ]
