# Generated by Django 6.0.3 on 2026-04-04 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_paymentgateway_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSenderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is this sender ID active for the user?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_id', models.ForeignKey(help_text='Assigned sender ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.senderid')),
                ('user', models.ForeignKey(help_text='User who owns this sender ID', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sender_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sender ID',
                'verbose_name_plural': 'User Sender IDs',
                'db_table': 'user_sender_ids',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'sender_id')},
            },
        ),
    ]
