# Generated by Django 6.0.3 on 2026-04-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_user_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_provider',
            field=models.ForeignKey(blank=True, help_text='Default SMS provider for this user. If not set, system default will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='core.smsprovider'),
        ),
    ]
