# Generated by Django 6.0.3 on 2026-04-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='The API key', max_length=100, unique=True)),
                ('name', models.CharField(default='Default', help_text='Name/description for this API key', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this API key active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date (null for no expiration)', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Phone number', max_length=20)),
                ('message', models.TextField()),
                ('sender_id', models.CharField(default='NanoMailer', max_length=20)),
                ('message_type', models.CharField(choices=[('masking', 'Masking'), ('non_masking', 'Non-Masking')], default='masking', help_text='Auto-detected from sender_id: numeric=non-masking, alphabetic=masking', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('message_id', models.CharField(blank=True, help_text='Gateway message ID', max_length=100, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('segments', models.PositiveIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('operator', models.CharField(choices=[('grameenphone', 'Grameenphone'), ('banglalink', 'Banglalink'), ('robi', 'Robi'), ('airtel', 'Airtel'), ('teletalk', 'Teletalk'), ('unknown', 'Unknown')], default='unknown', help_text='Mobile operator identified from recipient number', max_length=20)),
                ('balance_deducted', models.BooleanField(default=False, help_text='Whether balance has been deducted for this SMS')),
                ('deducted_amount', models.DecimalField(decimal_places=4, default=0, help_text='Amount deducted from user balance', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='core.smsprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'db_table': 'sms_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sender_id', models.CharField(default='NanoMailer', max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.smsprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Queue',
                'verbose_name_plural': 'SMS Queues',
                'db_table': 'sms_queues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSMSRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('grameenphone', 'Grameenphone'), ('banglalink', 'Banglalink'), ('robi', 'Robi'), ('airtel', 'Airtel'), ('teletalk', 'Teletalk')], default='grameenphone', help_text='Mobile operator', max_length=20)),
                ('message_type', models.CharField(choices=[('masking', 'Masking'), ('non_masking', 'Non-Masking')], default='masking', help_text='Type of SMS', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per SMS in BDT', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User SMS Rate',
                'verbose_name_plural': 'User SMS Rates',
                'db_table': 'user_sms_rates',
                'ordering': ['user', 'operator', 'message_type'],
                'unique_together': {('user', 'operator', 'message_type')},
            },
        ),
    ]
