# Generated by Django 6.0.3 on 2026-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='profit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Profit = user cost - provider cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='smslog',
            name='provider_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Provider cost per SMS (from provider masking/non-masking rates)', max_digits=10),
        ),
    ]
