# Generated by Django 6.0.3 on 2026-04-03 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_gateway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSMSRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('default', 'Default (All Operators)'), ('grameenphone', 'Grameenphone'), ('banglalink', 'Banglalink'), ('robi', 'Robi'), ('airtel', 'Airtel'), ('teletalk', 'Teletalk')], default='default', help_text='Mobile operator', max_length=20)),
                ('message_type', models.CharField(choices=[('masking', 'Masking'), ('non_masking', 'Non-Masking')], default='masking', help_text='Type of SMS', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per SMS in BDT', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User SMS Rate',
                'verbose_name_plural': 'User SMS Rates',
                'db_table': 'user_sms_rates',
                'ordering': ['user', 'operator', 'message_type'],
                'unique_together': {('user', 'operator', 'message_type')},
            },
        ),
    ]
