# Generated by Django 6.0.3 on 2026-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_gateway', '0002_usersmsrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmsrate',
            name='operator',
            field=models.CharField(choices=[('grameenphone', 'Grameenphone'), ('banglalink', 'Banglalink'), ('robi', 'Robi'), ('airtel', 'Airtel'), ('teletalk', 'Teletalk')], default='grameenphone', help_text='Mobile operator', max_length=20),
        ),
    ]
