# Generated by Django 6.0.3 on 2026-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_gateway', '0003_remove_default_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='balance_deducted',
            field=models.BooleanField(default=False, help_text='Whether balance has been deducted for this SMS'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='deducted_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount deducted from user balance', max_digits=10),
        ),
        migrations.AddField(
            model_name='smslog',
            name='operator',
            field=models.CharField(choices=[('grameenphone', 'Grameenphone'), ('banglalink', 'Banglalink'), ('robi', 'Robi'), ('airtel', 'Airtel'), ('teletalk', 'Teletalk'), ('unknown', 'Unknown')], default='unknown', help_text='Mobile operator identified from recipient number', max_length=20),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
