# Generated by Django 6.0.3 on 2026-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_gateway', '0005_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='message_type',
            field=models.CharField(choices=[('masking', 'Masking'), ('non_masking', 'Non-Masking')], default='masking', help_text='Auto-detected from sender_id: numeric=non-masking, alphabetic=masking', max_length=20),
        ),
    ]
