# Generated by Django 6.0.3 on 2026-04-03 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_paymentgateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique transaction ID', max_length=100, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Gateway transaction ID', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Base amount', max_digits=10)),
                ('tdr_amount', models.DecimalField(decimal_places=2, default=0, help_text='TDR amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount with TDR', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('VALIDATED', 'Validated')], default='PENDING', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Raw gateway response')),
                ('validation_response', models.JSONField(blank=True, default=dict, help_text='Validation response')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.paymentgateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
