name: 🚀 CD-DEV

on:
  push:
    branches:
      - main

jobs:
  gateway_deployment:
    name: 🎉 Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'wr_deploy'

      - name: 🚚 Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Run Deployment Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            cd /home/NanoMailer-SMS-Gateway
            git stash && git pull origin main
            cd /home/NanoMailer-SMS-Gateway && chmod +x *.sh && sh deploy.sh
